# Generated by Django 2.0.7 on 2018-08-31 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=False, verbose_name='account is activated')),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(decimal_places=5, default=0, help_text='level 1 referrer', max_digits=19)),
                ('t2', models.DecimalField(decimal_places=5, default=0, help_text='level 2 referrer', max_digits=19)),
                ('t3', models.DecimalField(decimal_places=5, default=0, help_text='level 3 referrer', max_digits=19)),
                ('total_now', models.DecimalField(decimal_places=5, default=0, help_text='current total bonus', max_digits=19)),
                ('limit', models.DecimalField(decimal_places=5, default=0, help_text='limit of total bonus', max_digits=19)),
                ('last_update', models.DateTimeField(verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coins', models.DecimalField(decimal_places=5, default=0, max_digits=19)),
                ('rcode', models.CharField(blank=True, max_length=32)),
                ('last_update', models.DateTimeField(verbose_name='update time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
