# Generated by Django 2.0.7 on 2018-08-31 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufrom', models.IntegerField()),
                ('uto', models.IntegerField()),
                ('level', models.SmallIntegerField(default=0)),
                ('coins', models.DecimalField(decimal_places=5, default=0, max_digits=19)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='auditlog',
            unique_together={('ufrom', 'uto')},
        ),
    ]
